In [2]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\dell\anaconda3\lib\site-packages (4.17.2)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (0.24.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (0.11.1)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (2023.7.22)
Requirement already satisfied: typing_extensions>=4.9.0 in c:\users\dell\anaconda3\lib\site-packages (from selenium) (4.9.0)
Requirement already satisfied: attrs>=20.1.0 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\dell\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: wsproto>=0.14 in c:\users\dell\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\dell\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\dell\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\dell\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [14]:
import selenium
import pandas as pd
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [3]:
driver = webdriver.Chrome()

In [4]:
driver.get("https://www.shine.com/")

In [5]:
job_title=[]
job_location=[]
company_name=[]
experience_required=[]

In [5]:
title_tags=driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard__jjUmu  white-box-border jobCard"]')
for i in title_tags:
    title=i.text
    job_title.append(title)
    
location_tags=driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_locationIcon__zrWt2"]')
for i in location_tags:
    location=i.text
    job_location.append(location)

company_tags=driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_lists__fdnsc"]')   
for i in company_tags:
    company=i.text
    company_name.append(company)
    
experience_tags=driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_jobIcon__3FB1t"]')
for i in experience_tags:
    exp=i.text
    experience_required.append(exp)

In [6]:
print(len(job_title),len(job_location),len(company_name),len(experience_required))

60 60 60 60

In [7]:
import pandas as pd
df=pd.DataFrame({'Title':job_title,'Location':job_location,'Company_name':company_name,'Experience':experience_required})
df

,Title,Location,Company_name,Experience
0,,,,
1,Premium\n4 days ago\nReq. for the Technology A...,Pune,3 to 7 Yrs\nPune,3 to 7 Yrs
2,Premium\n4 days ago\nWe need Process Lead\ninf...,Chennai,0 to 5 Yrs\nChennai,0 to 5 Yrs
3,Premium\n4 days ago\nWe need Technical Operati...,Bangalore,2 to 4 Yrs\nBangalore,2 to 4 Yrs
4,,,,
5,,,,
6,,,,
7,Hot\n2 days ago\nData Entry Operator\nv-tech d...,Davanagere\n+9,0 to 1 Yr\nDavanagere\n+9,0 to 1 Yr
8,Hot\n2 days ago\nData Entry Executive\nv-tech ...,Idukki\n+9,0 to 1 Yr\nIdukki\n+9,0 to 1 Yr
9,Hot\n2 days ago\nData Entry Executive\nv-tech ...,Bangalore\n+9,0 to 1 Yr\nBangalore\n+9,0 to 1 Yr
10,,,,
11,,,,
12,Hot\n2 days ago\nRecruiter Execuive\naasaanjob...,Mumbai City,1 to 3 Yrs\nMumbai City,1 to 3 Yrs
13,4 days ago\nImmediate Openings For Testing\ndi...,Singapore\n+1,0 to 4 Yrs\nSingapore\n+1,0 to 4 Yrs
14,4 days ago\nWalk-in Interview for Tele Calling...,Bangalore,0 to 4 Yrs\nBangalore,0 to 4 Yrs
15,,,,
16,,,,
17,,,,
18,Hot\n0 days ago\nTrainee Product Specialist - ...,Other Karnataka,0 to 4 Yrs\nOther Karnataka,0 to 4 Yrs
19,Hot\n0 days ago\nSr. Nodejs Developer\nmobile ...,Chennai\n+1,7 to 11 Yrs\nChennai\n+1,7 to 11 Yrs
20,Hot\n0 days ago\nNodeJS Developer\ncollege dun...,Other Haryana,1 to 4 Yrs\nOther Haryana,1 to 4 Yrs
21,,,,
22,,,,
23,,,,
24,,,,
25,,,,
26,,,,
27,,,,
28,,,,
29,,,,
30,,,,
31,,,,
32,,,,
33,,,,
34,,,,
35,,,,
36,,,,
37,,,,
38,,,,
39,,,,
40,,,,
41,,,,
42,,,,
43,,,,
44,,,,
45,,,,
46,,,,
47,,,,
48,,,,
49,,,,
50,,,,
51,,,,
52,,,,
53,,,,
54,,,,
55,,,,
56,,,,
57,,,,
58,,,,
59,,,,

QUESTION 2

In [6]:
driver = webdriver.Chrome()

In [14]:
driver.get("https://www.shine.com/")

In [15]:
job_title=[]
job_location=[]
company_name=[]
experience_required=[]

In [20]:
title_tags=driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_features__wJid6"]')
for i in title_tags:
    title=i.text
    job_title.append(title)
    
location_tags=driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_locationIcon__zrWt2"]')
for i in location_tags:
    location=i.text
    job_location.append(location)

In [21]:
print(len(job_title),len(job_location))

20 20

In [22]:
import pandas as pd
df=pd.DataFrame({'Title':job_title,'Location':job_location})
df

                   Title        Location
0             1 week ago   Bangalore\n+4
1    Premium\n1 week ago       Bangalore
2            1 month ago   Bangalore\n+1
3            3 weeks ago   Bangalore\n+1
4            3 weeks ago  Bangalore\n+14
5            3 weeks ago   Bangalore\n+1
6            1 month ago   Bangalore\n+7
7            1 month ago  Bangalore\n+14
8            1 month ago   Bangalore\n+2
9            1 month ago   Bangalore\n+4
10           1 month ago  Bangalore\n+13
11           1 month ago  Bangalore\n+14
12           1 month ago  Bangalore\n+13
13           1 month ago  Bangalore\n+13
14  Premium\n1 month ago   Bangalore\n+8
15           1 month ago       Bangalore
16   Premium\n5 days ago   Bangalore\n+1
17            5 days ago       Bangalore
18   Premium\n4 days ago       Bangalore
19            5 days ago       Bangalore

QUESTION 3

In [7]:
driver = webdriver.Chrome()

In [8]:
driver.get("https://www.shine.com/")

In [9]:
job_title=[]
job_location=[]
company_name=[]
experience_required=[]

In [10]:
title_tags=driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard__jjUmu  white-box-border jobCard"]')
for i in title_tags:
    title=i.text
    job_title.append(title)
    
location_tags=driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_locationIcon__zrWt2"]')
for i in location_tags:
    location=i.text
    job_location.append(location)

company_tags=driver.find_elements(By.XPATH,'//div[@class="jobCard_jobCard_cName__mYnow"]')   
for i in company_tags:
    company=i.text
    company_name.append(company)
    
experience_tags=driver.find_elements(By.XPATH,'//div[@class=" jobCard_jobCard_lists_item__YxRkV jobCard_jobIcon__3FB1t"]')
for i in experience_tags:
    exp=i.text
    experience_required.append(exp)

In [11]:
print(len(job_title),len(job_location),len(company_name),len(experience_required))

19 20 20 20

QUESTION 4

In [23]:
driver = webdriver.Chrome()

In [24]:
driver.get("https://www.flipkart.com/")

In [37]:
Brand=[]
Price=[]
Product_description=[]

In [38]:
brand_tags=driver.find_elements(By.XPATH,'//div[@class="_25b18c"]')
for i in brand_tags:
    brand=i.text
    Brand.append(brand)
    
price_tags=driver.find_elements(By.XPATH,'//a[@class="_3bPFwb"]')
for i in price_tags:
    price=i.text
    Price.append(price)

product_description_tags=driver.find_elements(By.XPATH, '//a[@class="IRpwTa"]')
for i in product_description_tags:
    product_description=i.text
    Product_description.append(product_description)

QUESTION 5

In [44]:
driver = webdriver.Chrome()

In [42]:
driver.get("https://www.flipkart.com/")

In [43]:
Brand=[]
Price=[]
Product_description=[]

In [46]:
brand_tags=driver.find_elements(By.XPATH,'//div[@class="_25b18c"]')
for i in brand_tags:
    brand=i.text
    Brand.append(brand)
    
price_tags=driver.find_elements(By.XPATH,'//a[@class="_3bPFwb"]')
for i in price_tags:
    price=i.text
    Price.append(price)

product_description_tags=driver.find_elements(By.XPATH, '//a[@class="IRpwTa"]')
for i in product_description_tags:
    product_description=i.text
    Product_description.append(product_description)

QUESTION 6

In [47]:
driver = webdriver.Chrome()

In [48]:
driver.get("https://www.flipkart.com/")

In [49]:
Brand=[]
Price=[]
Product_description=[]

In [52]:
brand_tags=driver.find_elements(By.XPATH,'//div[@class="_2WkVRV"]')
for i in brand_tags:
    brand=i.text
    Brand.append(brand)
    
price_tags=driver.find_elements(By.XPATH,'//a[@class="_3bPFwb"]')
for i in price_tags:
    price=i.text
    Price.append(price)

product_description_tags=driver.find_elements(By.XPATH, '//a[@class="IRpwTa"]')
for i in product_description_tags:
    product_description=i.text
    Product_description.append(product_description)

WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=120.0.6099.225)
Stacktrace:
	GetHandleVerifier [0x00007FF63D1A2142+3514994]
	(No symbol) [0x00007FF63CDC0CE2]
	(No symbol) [0x00007FF63CC676AA]
	(No symbol) [0x00007FF63CC4FD6A]
	(No symbol) [0x00007FF63CC4FC20]
	(No symbol) [0x00007FF63CC699A1]
	(No symbol) [0x00007FF63CCF21B7]
	(No symbol) [0x00007FF63CCD5D93]
	(No symbol) [0x00007FF63CCA4BDC]
	(No symbol) [0x00007FF63CCA5C64]
	GetHandleVerifier [0x00007FF63D1CE16B+3695259]
	GetHandleVerifier [0x00007FF63D226737+4057191]
	GetHandleVerifier [0x00007FF63D21E4E3+4023827]
	GetHandleVerifier [0x00007FF63CEF04F9+689705]
	(No symbol) [0x00007FF63CDCC048]
	(No symbol) [0x00007FF63CDC8044]
	(No symbol) [0x00007FF63CDC81C9]
	(No symbol) [0x00007FF63CDB88C4]
	BaseThreadInitThunk [0x00007FFFB964257D+29]
	RtlUserThreadStart [0x00007FFFBAC4AA58+40]

QUESTION 7

In [15]:
driver = webdriver.Chrome()

In [16]:
driver.get("https://www.amazon.in")

In [17]:
    Title=[]
    Ratings=[]
    Price=[]

In [ ]:
title_tags=driver.find_elements(By.XPATH,'//span[@class="a-size-medium a-color-base a-text-normal"]')
for i in title_tags:
    title=i.text
    Title.append(title)
    
ratings_tags=driver.find_elements(By.XPATH,'//i[@class="a-icon a-icon-star-small a-star-small-4 aok-align-bottom"]')
for i in ratings_tags:
    ratings=i.text
    Ratings.append(ratings)

price_tags=driver.find_elements(By.XPATH,'//span[@class="a-price-whole"]')
for i in price_tags:
   price=i.text
  Price.append(price)

QUESTION 8

In [10]:
driver = webdriver.Chrome()

In [11]:
driver.get("https://www.azquotes.com/")

In [8]:
Author=[]
Quotes=[]
Types_of_quotes=[]

In [ ]:
author_tags=driver.find_elements(By.XPATH,'//div[@class="author"]')
for i in author_tags:
    author=i.text
    Author.append(author)
    
quotes_tags=driver.find_elements(By.XPATH,'//a[@class="title"]')
for i in quotes_tags:
    quotes=i.text
    Quotes.append(quotes)

types_of_quotes_tags=driver.find_elements(By.XPATH,'//div[@class="tags"]')
for i in types_of_quotes_tags:
   types_of_quotes=i.text
  Types_of_quotes.append(types_of_quotes)

QUESTION 9

In [15]:
driver = webdriver.Chrome()

In [18]:
driver.get("https://www.jagranjosh.com/")